openapi: 3.0.3
info:
  title: 'API для покупки билетов'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/order:
    post:
      summary: 'Создание нового заказа.'
      operationId: ''
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                event_id:
                  type: integer
                  description: ''
                  example: 12
                event_date:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2024-10-30T18:02:46'
                ticket_adult_price:
                  type: integer
                  description: ''
                  example: 7
                ticket_adult_quantity:
                  type: integer
                  description: ''
                  example: 13
                ticket_kid_price:
                  type: integer
                  description: ''
                  example: 12
                ticket_kid_quantity:
                  type: integer
                  description: ''
                  example: 8
                ticket_concessionary_price:
                  type: integer
                  description: 'This field is required when <code>ticket_concessionary_quantity</code> is present.'
                  example: 13
                ticket_concessionary_quantity:
                  type: integer
                  description: ''
                  example: 14
                ticket_group_price:
                  type: integer
                  description: 'This field is required when <code>ticket_group_quantity</code> is present.'
                  example: 7
                ticket_group_quantity:
                  type: integer
                  description: ''
                  example: 19
              required:
                - event_id
                - event_date
                - ticket_adult_price
                - ticket_adult_quantity
                - ticket_kid_price
                - ticket_kid_quantity
      security: []
tags:
  -
    name: Endpoints
    description: ''
